# Generated by Django 5.0.6 on 2026-05-30 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'rbac_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('user', 'User'), ('role', 'Role'), ('access_rule', 'Access Rule')], max_length=50)),
                ('can_read', models.BooleanField(default=False, help_text='Can read objects owned by self.')),
                ('can_read_all', models.BooleanField(default=False, help_text='Can read any object of this resource.')),
                ('can_create', models.BooleanField(default=False, help_text='Can create new objects of this resource.')),
                ('can_update', models.BooleanField(default=False, help_text='Can update objects owned by self.')),
                ('can_update_all', models.BooleanField(default=False, help_text='Can update any object of this resource.')),
                ('can_delete', models.BooleanField(default=False, help_text='Can delete objects owned by self.')),
                ('can_delete_all', models.BooleanField(default=False, help_text='Can delete any object of this resource.')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='rbac.role')),
            ],
            options={
                'verbose_name': 'Access Rule',
                'verbose_name_plural': 'Access Rules',
                'db_table': 'rbac_accessrule',
                'unique_together': {('role', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who granted this role. Null if assigned via seed/system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'rbac_userrole',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
